# Generated by Django 3.2.4 on 2022-03-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_apps_output_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='week',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
