# Generated by Django 3.2.4 on 2022-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20220313_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='topic',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
